branch-defaults:
  master:
    environment: null
global:
  application_name: melvinopolis
  default_ec2_keyname: aws-eb
  default_platform: Ruby 2.2 (Puma)
  default_region: us-east-1
  profile: eb-cli
  sc: git
